// Code generated by Thrift Compiler (0.14.1). DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	"github.com/apache/thrift/lib/go/thrift"
	"secondaryqrcodeloginservice"
)

var _ = secondaryqrcodeloginservice.GoUnusedProtection__

func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  CreateQrSessionResponse createSession(CreateQrSessionRequest request)")
  fmt.Fprintln(os.Stderr, "  CreateQrCodeResponse createQrCode(CreateQrCodeRequest request)")
  fmt.Fprintln(os.Stderr, "  CreatePinCodeResponse createPinCode(CreatePinCodeRequest request)")
  fmt.Fprintln(os.Stderr, "  VerifyCertificateResponse verifyCertificate(VerifyCertificateRequest request)")
  fmt.Fprintln(os.Stderr, "  QrCodeLoginResponse qrCodeLogin(QrCodeLoginRequest request)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
  var m map[string]string = h
  return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
  parts := strings.Split(value, ": ")
  if len(parts) != 2 {
    return fmt.Errorf("header should be of format 'Key: Value'")
  }
  h[parts[0]] = parts[1]
  return nil
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  headers := make(httpHeaders)
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
    if len(headers) > 0 {
      httptrans := trans.(*thrift.THttpClient)
      for key, value := range headers {
        httptrans.SetHeader(key, value)
      }
    }
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := secondaryqrcodeloginservice.NewSecondaryQrCodeLoginServiceClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "createSession":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "CreateSession requires 1 args")
      flag.Usage()
    }
    arg20 := flag.Arg(1)
    mbTrans21 := thrift.NewTMemoryBufferLen(len(arg20))
    defer mbTrans21.Close()
    _, err22 := mbTrans21.WriteString(arg20)
    if err22 != nil {
      Usage()
      return
    }
    factory23 := thrift.NewTJSONProtocolFactory()
    jsProt24 := factory23.GetProtocol(mbTrans21)
    argvalue0 := secondaryqrcodeloginservice.NewCreateQrSessionRequest()
    err25 := argvalue0.Read(context.Background(), jsProt24)
    if err25 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.CreateSession(context.Background(), value0))
    fmt.Print("\n")
    break
  case "createQrCode":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "CreateQrCode requires 1 args")
      flag.Usage()
    }
    arg26 := flag.Arg(1)
    mbTrans27 := thrift.NewTMemoryBufferLen(len(arg26))
    defer mbTrans27.Close()
    _, err28 := mbTrans27.WriteString(arg26)
    if err28 != nil {
      Usage()
      return
    }
    factory29 := thrift.NewTJSONProtocolFactory()
    jsProt30 := factory29.GetProtocol(mbTrans27)
    argvalue0 := secondaryqrcodeloginservice.NewCreateQrCodeRequest()
    err31 := argvalue0.Read(context.Background(), jsProt30)
    if err31 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.CreateQrCode(context.Background(), value0))
    fmt.Print("\n")
    break
  case "createPinCode":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "CreatePinCode requires 1 args")
      flag.Usage()
    }
    arg32 := flag.Arg(1)
    mbTrans33 := thrift.NewTMemoryBufferLen(len(arg32))
    defer mbTrans33.Close()
    _, err34 := mbTrans33.WriteString(arg32)
    if err34 != nil {
      Usage()
      return
    }
    factory35 := thrift.NewTJSONProtocolFactory()
    jsProt36 := factory35.GetProtocol(mbTrans33)
    argvalue0 := secondaryqrcodeloginservice.NewCreatePinCodeRequest()
    err37 := argvalue0.Read(context.Background(), jsProt36)
    if err37 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.CreatePinCode(context.Background(), value0))
    fmt.Print("\n")
    break
  case "verifyCertificate":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "VerifyCertificate requires 1 args")
      flag.Usage()
    }
    arg38 := flag.Arg(1)
    mbTrans39 := thrift.NewTMemoryBufferLen(len(arg38))
    defer mbTrans39.Close()
    _, err40 := mbTrans39.WriteString(arg38)
    if err40 != nil {
      Usage()
      return
    }
    factory41 := thrift.NewTJSONProtocolFactory()
    jsProt42 := factory41.GetProtocol(mbTrans39)
    argvalue0 := secondaryqrcodeloginservice.NewVerifyCertificateRequest()
    err43 := argvalue0.Read(context.Background(), jsProt42)
    if err43 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.VerifyCertificate(context.Background(), value0))
    fmt.Print("\n")
    break
  case "qrCodeLogin":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "QrCodeLogin requires 1 args")
      flag.Usage()
    }
    arg44 := flag.Arg(1)
    mbTrans45 := thrift.NewTMemoryBufferLen(len(arg44))
    defer mbTrans45.Close()
    _, err46 := mbTrans45.WriteString(arg44)
    if err46 != nil {
      Usage()
      return
    }
    factory47 := thrift.NewTJSONProtocolFactory()
    jsProt48 := factory47.GetProtocol(mbTrans45)
    argvalue0 := secondaryqrcodeloginservice.NewQrCodeLoginRequest()
    err49 := argvalue0.Read(context.Background(), jsProt48)
    if err49 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.QrCodeLogin(context.Background(), value0))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
